//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Naudotojo kortelės nuskaitymo įvykio klasė.
    /// </summary>
    public partial class Entry
    {
        public long id { get; set; }
        public string user_id { get; set; }
        public string card_id { get; set; }
        public string user_name { get; set; }
        public string direction { get; set; }
        public string device_name { get; set; }
        public string device_serial_no { get; set; }
        public Nullable<System.DateTime> auth_datetime { get; set; }
        public Nullable<System.DateTime> auth_date { get; set; }
        public Nullable<System.TimeSpan> auth_time { get; set; }
    }
}
