//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Sistemos nustatymų klasė.
    /// </summary>
    public partial class Setting
    {
        public int id { get; set; }
        public string NVRIP { get; set; }
        public Nullable<int> NVRPort { get; set; }
        public string NVRUsername { get; set; }
        public string NVRPassword { get; set; }
        public string AccessControllerIP { get; set; }
        public Nullable<int> AccessControllerPort { get; set; }
        public string AccessControllerUsername { get; set; }
        public string AccessControllerPassword { get; set; }
    }
}
