//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarboLaikoSkaiciavimoSistema.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarboLaikoSkaiciavimoSistema.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time Tracking System.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string btnForgotPassword {
            get {
                return ResourceManager.GetString("btnForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video feed.
        /// </summary>
        public static string btnLiveFeed {
            get {
                return ResourceManager.GetString("btnLiveFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera recordings.
        /// </summary>
        public static string btnRecordings {
            get {
                return ResourceManager.GetString("btnRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register user.
        /// </summary>
        public static string btnRegisterUser {
            get {
                return ResourceManager.GetString("btnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string btnResetPassword {
            get {
                return ResourceManager.GetString("btnResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string btnSendCode {
            get {
                return ResourceManager.GetString("btnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time statistics.
        /// </summary>
        public static string btnStatistics {
            get {
                return ResourceManager.GetString("btnStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee list.
        /// </summary>
        public static string btnUsers {
            get {
                return ResourceManager.GetString("btnUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string cbRememberMe {
            get {
                return ResourceManager.GetString("cbRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access controller error!.
        /// </summary>
        public static string errAccessController {
            get {
                return ResourceManager.GetString("errAccessController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified card number is taken!.
        /// </summary>
        public static string errCardIdTaken {
            get {
                return ResourceManager.GetString("errCardIdTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error!.
        /// </summary>
        public static string errDatabase {
            get {
                return ResourceManager.GetString("errDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all of the fields!.
        /// </summary>
        public static string errEmptyFields {
            get {
                return ResourceManager.GetString("errEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address!.
        /// </summary>
        public static string errInvalidEmail {
            get {
                return ResourceManager.GetString("errInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti vaizdo medžiagos!.
        /// </summary>
        public static string errNoVideo {
            get {
                return ResourceManager.GetString("errNoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered passwords do not match!.
        /// </summary>
        public static string errPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("errPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered password is too weak!.
        /// </summary>
        public static string errPasswordTooWeak {
            get {
                return ResourceManager.GetString("errPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password reset code.
        /// </summary>
        public static string errResetCode {
            get {
                return ResourceManager.GetString("errResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time value must be lower than the end time value!.
        /// </summary>
        public static string errTime {
            get {
                return ResourceManager.GetString("errTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string errTitle {
            get {
                return ResourceManager.GetString("errTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user data!.
        /// </summary>
        public static string errUser {
            get {
                return ResourceManager.GetString("errUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is taken!.
        /// </summary>
        public static string errUsernameTaken {
            get {
                return ResourceManager.GetString("errUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string errWrongCredentials {
            get {
                return ResourceManager.GetString("errWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset code will be sent to the provided address if it is registered.
        /// </summary>
        public static string infoCodeSent {
            get {
                return ResourceManager.GetString("infoCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed!.
        /// </summary>
        public static string infoPasswordChanged {
            get {
                return ResourceManager.GetString("infoPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings successfully saved.
        /// </summary>
        public static string infoSettingsSaved {
            get {
                return ResourceManager.GetString("infoSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string infoTitle {
            get {
                return ResourceManager.GetString("infoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee registered successfully!.
        /// </summary>
        public static string infoUserRegistered {
            get {
                return ResourceManager.GetString("infoUserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access controller IP address.
        /// </summary>
        public static string lblAccessControllerIP {
            get {
                return ResourceManager.GetString("lblAccessControllerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access controller password.
        /// </summary>
        public static string lblAccessControllerPassword {
            get {
                return ResourceManager.GetString("lblAccessControllerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access controller port.
        /// </summary>
        public static string lblAccessControllerPort {
            get {
                return ResourceManager.GetString("lblAccessControllerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access controller username.
        /// </summary>
        public static string lblAccessControllerUsername {
            get {
                return ResourceManager.GetString("lblAccessControllerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lblAccessLevel {
            get {
                return ResourceManager.GetString("lblAccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string lblCardNumber {
            get {
                return ResourceManager.GetString("lblCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera ID.
        /// </summary>
        public static string lblChannel {
            get {
                return ResourceManager.GetString("lblChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string lblConfirmNewPassword {
            get {
                return ResourceManager.GetString("lblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video footage end time:.
        /// </summary>
        public static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra time this month:.
        /// </summary>
        public static string lblExtraTimeMonthLabel {
            get {
                return ResourceManager.GetString("lblExtraTimeMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVR IP address.
        /// </summary>
        public static string lblNVRIP {
            get {
                return ResourceManager.GetString("lblNVRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVR password.
        /// </summary>
        public static string lblNVRPassword {
            get {
                return ResourceManager.GetString("lblNVRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVR RTSP port.
        /// </summary>
        public static string lblNVRPort {
            get {
                return ResourceManager.GetString("lblNVRPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVR username.
        /// </summary>
        public static string lblNVRUsername {
            get {
                return ResourceManager.GetString("lblNVRUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to consist of:
        ///• At least 8 symbols
        ///• At least one lowercase letter
        ///• At least one uppercase letter
        ///• At least one numeric symbol.
        /// </summary>
        public static string lblPasswordRequirements {
            get {
                return ResourceManager.GetString("lblPasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining working time this month:.
        /// </summary>
        public static string lblRemainingTimeMonthLabel {
            get {
                return ResourceManager.GetString("lblRemainingTimeMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining working time today:.
        /// </summary>
        public static string lblRemainingTimeTodayLabel {
            get {
                return ResourceManager.GetString("lblRemainingTimeTodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining working time this week:.
        /// </summary>
        public static string lblRemainingTimeWeekLabel {
            get {
                return ResourceManager.GetString("lblRemainingTimeWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset code.
        /// </summary>
        public static string lblResetCode {
            get {
                return ResourceManager.GetString("lblResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset code will be sent to your email address. 
        ///Be sure to check the spam folder..
        /// </summary>
        public static string lblResetCodeInfo {
            get {
                return ResourceManager.GetString("lblResetCodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video footage start time:.
        /// </summary>
        public static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time worked this month (h).
        /// </summary>
        public static string lblTimeWorkedThisMonth {
            get {
                return ResourceManager.GetString("lblTimeWorkedThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time worked this week (h).
        /// </summary>
        public static string lblTimeWorkedThisWeek {
            get {
                return ResourceManager.GetString("lblTimeWorkedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work hours per week:.
        /// </summary>
        public static string lblWorkHoursPerWeek {
            get {
                return ResourceManager.GetString("lblWorkHoursPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string loginViewName {
            get {
                return ResourceManager.GetString("loginViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string mainViewName {
            get {
                return ResourceManager.GetString("mainViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string passwordResetViewName {
            get {
                return ResourceManager.GetString("passwordResetViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string settingsViewName {
            get {
                return ResourceManager.GetString("settingsViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time statistics.
        /// </summary>
        public static string statisticsViewName {
            get {
                return ResourceManager.GetString("statisticsViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee information.
        /// </summary>
        public static string userEditViewName {
            get {
                return ResourceManager.GetString("userEditViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Employees.
        /// </summary>
        public static string userListViewName {
            get {
                return ResourceManager.GetString("userListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee registration.
        /// </summary>
        public static string userRegistrationViewName {
            get {
                return ResourceManager.GetString("userRegistrationViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source selection.
        /// </summary>
        public static string videoSourceViewName {
            get {
                return ResourceManager.GetString("videoSourceViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera {0} video recording (From {1} to {2}).
        /// </summary>
        public static string videoViewRecordingName {
            get {
                return ResourceManager.GetString("videoViewRecordingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera {0} live feed.
        /// </summary>
        public static string videoViewStreamName {
            get {
                return ResourceManager.GetString("videoViewStreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string warningDeleteUser {
            get {
                return ResourceManager.GetString("warningDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save new user information?.
        /// </summary>
        public static string warningEditUser {
            get {
                return ResourceManager.GetString("warningEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string warningLogout {
            get {
                return ResourceManager.GetString("warningLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warningTitle {
            get {
                return ResourceManager.GetString("warningTitle", resourceCulture);
            }
        }
    }
}
